{{- if and .Values.hpa .Values.hpa.enabled }}

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler

metadata:
  name: {{ default "employeeprofileapp" .Values.app.name }}-hpa

spec:

  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}

  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ default "employeeprofileapp" .Values.app.name }}

  metrics:

    # =====================================
    # CPU METRIC
    # =====================================

    - type: Resource

      resource:
        name: cpu

        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.averageUtilization }}

    # =====================================
    # OPTIONAL MEMORY METRIC
    # =====================================

    {{- if .Values.hpa.memoryAverageUtilization }}

    - type: Resource

      resource:
        name: memory

        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.memoryAverageUtilization }}

    {{- end }}

  # =====================================
  # OPTIONAL SCALING BEHAVIOR
  # =====================================

  behavior:

    scaleUp:

      stabilizationWindowSeconds: {{ .Values.hpa.stabilizationWindowSeconds | default 300 }}

      policies:

      - type: Percent
        value: 100
        periodSeconds: 60

    scaleDown:

      stabilizationWindowSeconds: {{ .Values.hpa.stabilizationWindowSeconds | default 300 }}

      policies:

      - type: Percent
        value: 50
        periodSeconds: 60

{{- end }}