{{- if and .Values.hpa .Values.hpa.enabled }}

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler

metadata:
  name: {{ default "employeeprofileapp" .Values.app.name }}-hpa

spec:

  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}

  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ default "employeeprofileapp" .Values.app.name }}

  metrics:

    # =====================================
    # CPU METRIC
    # =====================================

    - type: Resource

      resource:
        name: cpu

        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.averageUtilization }}

    # =====================================
    # OPTIONAL MEMORY METRIC
    # Only used if configured
    # =====================================

    {{- if .Values.hpa.memoryAverageUtilization }}

    - type: Resource

      resource:
        name: memory

        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.memoryAverageUtilization }}

    {{- end }}

{{- end }}