{{- if .Values.keyVault.enabled }}

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass

metadata:
  name: {{ .Values.keyVault.secretProviderClass }}
  namespace: {{ .Release.Namespace }}

spec:

  provider: azure

  secretObjects:

    - secretName: {{ .Values.keyVault.k8sSecretName }}

      type: Opaque

      data:

        {{- range .Values.keyVault.secrets }}

        - objectName: {{ .objectName }}
          key: {{ .objectName }}

        {{- end }}

  parameters:

    # =====================================
    # AUTHENTICATION MODE
    # =====================================

    usePodIdentity: "false"

    useVMManagedIdentity: "true"

    # =====================================
    # USER ASSIGNED MANAGED IDENTITY
    # =====================================

    userAssignedIdentityID: "{{ .Values.keyVault.userAssignedIdentityID }}"

    # =====================================
    # AZURE KEY VAULT
    # =====================================

    keyvaultName: "{{ .Values.keyVault.keyVaultName }}"

    tenantId: "{{ .Values.keyVault.tenantId }}"

    cloudName: ""

    # =====================================
    # SECRETS
    # =====================================

    objects: |

      array:

        {{- range .Values.keyVault.secrets }}

        - |

          objectName: {{ .objectName }}

          objectType: {{ .objectType }}

          objectVersion: ""

        {{- end }}

{{- end }}