# =====================================
# FILE:
# helm/employeeprofileapp/templates/secretproviderclass.yaml
# VERSION:
# v17-enterprise-keyvault-csi-workloadidentity-production-final
# =====================================

{{- if and .Values.keyVault.enabled .Values.secretProviderClass.enabled }}

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass

metadata:
  name: {{ .Values.keyVault.secretProviderClass }}

  namespace: {{ .Values.namespaceOverride }}

  labels:
    app.kubernetes.io/name: {{ .Values.app.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "employeeprofileapp.chart" . }}

spec:
  provider: azure

  secretObjects:
    - secretName: {{ .Values.keyVault.k8sSecretName }}

      type: Opaque

      data:
        - objectName: db-username
          key: DB_USERNAME

        - objectName: db-password
          key: DB_PASSWORD

        - objectName: sql-server-name
          key: SQL_SERVER_NAME

        - objectName: sql-server-fqdn
          key: SQL_SERVER_FQDN

        - objectName: sql-database-name
          key: SQL_DATABASE_NAME

        - objectName: sql-connection-string
          key: SQL_CONNECTION_STRING

  parameters:
    usePodIdentity: "false"

    useVMManagedIdentity: "false"

    userAssignedIdentityID: ""

    clientID: {{ required "workloadIdentity.clientId is required" .Values.workloadIdentity.clientId | quote }}

    keyvaultName: {{ required "keyVault.keyVaultName is required" .Values.keyVault.keyVaultName | quote }}

    tenantId: {{ required "keyVault.tenantId is required" .Values.keyVault.tenantId | quote }}

    cloudName: {{ .Values.keyVault.cloudName | quote }}

    objects: |
      array:
        - |
          objectName: db-username
          objectType: secret

        - |
          objectName: db-password
          objectType: secret

        - |
          objectName: sql-server-name
          objectType: secret

        - |
          objectName: sql-server-fqdn
          objectType: secret

        - |
          objectName: sql-database-name
          objectType: secret

        - |
          objectName: sql-connection-string
          objectType: secret

{{- end }}