# =====================================
# FILE:
# helm/employeeprofileapp/templates/serviceaccount.yaml
# VERSION:
# v20-enterprise-workloadidentity-runtime-complete-final
# =====================================

{{- if .Values.serviceAccount.create }}

apiVersion: v1
kind: ServiceAccount

metadata:
  name: {{ .Values.serviceAccount.name }}

  namespace: {{ .Release.Namespace }}

  labels:
    app: {{ default .Chart.Name .Values.app.name }}

    app.kubernetes.io/name: {{ .Chart.Name }}

    app.kubernetes.io/instance: {{ .Release.Name }}

    app.kubernetes.io/managed-by: Helm

    managed-by: Helm

    {{- with .Values.podLabels }}
{{ toYaml . | indent 4 }}
    {{- end }}

  annotations:
    {{- if .Values.workloadIdentity.enabled }}

    azure.workload.identity/use: "true"

    azure.workload.identity/client-id: {{ required "workloadIdentity.clientId is required" .Values.workloadIdentity.clientId | quote }}

    azure.workload.identity/tenant-id: {{ required "workloadIdentity.tenantId is required" .Values.workloadIdentity.tenantId | quote }}

    {{- end }}

    {{- with .Values.serviceAccount.annotations }}
{{ toYaml . | indent 4 }}
    {{- end }}

automountServiceAccountToken: true

{{- end }}