replicaCount: 1

app:
  name: employeeprofileapp-qa

image:
  repository: prasidsash/employeeprofileapp-aks
  tag: v1
  pullPolicy: Always

env:
  ASPNETCORE_ENVIRONMENT: QA environment

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"

  limits:
    cpu: "200m"
    memory: "256Mi"

ingress:
  enabled: false
  className: ""
  host: ""
  path: /
  pathType: Prefix

hpa:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  averageUtilization: 70