# =====================================
# REPLICAS
# =====================================

replicaCount: 1

# =====================================
# APPLICATION
# =====================================

app:
  name: employeeprofileapp-dev

# =====================================
# IMAGE
# =====================================

image:
  repository: prasidsash/employeeprofileapp-aks
  tag: latest
  pullPolicy: Always

# =====================================
# SERVICE
# =====================================

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

# Optional feature toggle
serviceSettings:
  enableLoadBalancer: true

# =====================================
# ENVIRONMENT VARIABLES
# =====================================

env:
  ASPNETCORE_ENVIRONMENT: Development

# =====================================
# RESOURCE SETTINGS
# =====================================

resources:

  requests:
    cpu: "100m"
    memory: "128Mi"

  limits:
    cpu: "200m"
    memory: "256Mi"

# =====================================
# INGRESS
# =====================================

ingress:
  enabled: false
  className: ""
  host: ""
  path: /
  pathType: Prefix

# =====================================
# HPA
# =====================================

hpa:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  averageUtilization: 70

  # Optional future setting
  memoryAverageUtilization: null

# =====================================
# NAMESPACE
# =====================================

namespace: employeeprofileapp-dev

# =====================================
# IMAGE PULL SECRETS
# =====================================

imagePullSecrets: []

# =====================================
# PROBES
# =====================================

readinessProbe:
  enabled: false
  path: /
  port: 8080

livenessProbe:
  enabled: false
  path: /
  port: 8080