replicaCount: 3

app:
  name: employeeprofileapp

image:
  repository: prasidsash/employeeprofileapp
  tag: v1
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources:
  requests:
    cpu: "1"
    memory: "1Gi"

  limits:
    cpu: "2"
    memory: "2Gi"

ingress:
  enabled: true
  className: nginx
  host: employee.company.com
  path: /
  pathType: Prefix

hpa:
  enabled: true
  minReplicas: 3
  maxReplicas: 20
  averageUtilization: 70