name: $(Date:yyyyMMdd).$(Rev:r)

trigger:
  branches:
    include:
      - main

  paths:
    include:
      - src/**
      - helm/**
      - Dockerfile
      - azure-pipelines/app-ci.yaml

    exclude:
      - terraform/**
      - azure-pipelines/infra-pipeline.yml
      - README.md

pool:
  vmImage: ubuntu-latest

# =====================================
# VARIABLES
# =====================================

variables:

  - group: employeeprofileapp-dev-vars

  # =====================================
  # DOCKER HUB CONFIGURATION
  # =====================================

  - name: dockerRegistryServiceConnection
    value: 'Docker-SC'

  - name: imageRepository
    value: 'prasidsash/employeeprofileapp-aks'

# =====================================
# ACR CONFIGURATION
# =====================================

  - name: acrServiceConnection
    value: 'ACR-SC'

  - name: acrRepository
    value: 'employeeprofileapp-aks'

# =====================================
# STAGES
# =====================================

stages:

  - stage: BuildAndSecurityScan

    displayName: Build Scan And Push

    jobs:

      - job: DockerBuildScanPush

        displayName: Docker Build Scan Push

        steps:

          - checkout: self

          # =====================================
          # TOOLING VALIDATION
          # =====================================

          - script: |

              echo "=================================="
              echo "Docker Version"
              echo "=================================="

              docker --version

            displayName: Validate Docker Tooling

          # =====================================
          # BUILD INFORMATION
          # =====================================

          - script: |

              echo "=================================="
              echo "Build Information"
              echo "=================================="

              echo "Build Number: $(Build.BuildNumber)"
              echo "Source Branch: $(Build.SourceBranchName)"
              echo "ACR Enabled: $(enableAcr)"

            displayName: Build Metadata

          # =====================================
          # .NET RESTORE
          # =====================================

          - task: DotNetCoreCLI@2

            displayName: Dotnet Restore

            inputs:
              command: restore
              projects: 'src/Employeeprofileapp/EmployeeProfileApp.csproj'

          # =====================================
          # .NET BUILD
          # =====================================

          - task: DotNetCoreCLI@2

            displayName: Dotnet Build

            inputs:
              command: build
              projects: 'src/Employeeprofileapp/EmployeeProfileApp.csproj'
              arguments: '--configuration Release'

          # =====================================
          # .NET TEST
          # =====================================

          - task: DotNetCoreCLI@2

            displayName: Dotnet Test

            inputs:
              command: test
              projects: 'src/Employeeprofileapp/EmployeeProfileApp.csproj'
              arguments: '--configuration Release'

          # =====================================
          # INSTALL TRIVY
          # =====================================

          - script: |

              echo "=================================="
              echo "Install Trivy"
              echo "=================================="

              sudo apt-get update

              sudo apt-get install wget gnupg lsb-release apt-transport-https -y

              wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | \
              gpg --dearmor | \
              sudo tee /usr/share/keyrings/trivy.gpg > /dev/null

              echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | \
              sudo tee /etc/apt/sources.list.d/trivy.list

              sudo apt-get update

              sudo apt-get install trivy -y

            displayName: Install Trivy

          # =====================================
          # DOCKER HUB BUILD
          # =====================================

          - task: Docker@2

            displayName: Docker Hub Build

            condition: eq(lower(variables['enableAcr']), 'false')

            inputs:

              command: build

              containerRegistry: $(dockerRegistryServiceConnection)

              repository: $(imageRepository)

              dockerfile: '$(Build.SourcesDirectory)/Dockerfile'

              buildContext: '$(Build.SourcesDirectory)'

              tags: |
                $(Build.BuildNumber)
                latest

          # =====================================
          # DOCKER HUB PUSH
          # =====================================

          - task: Docker@2

            displayName: Docker Hub Push

            condition: eq(lower(variables['enableAcr']), 'false')

            inputs:

              command: push

              containerRegistry: $(dockerRegistryServiceConnection)

              repository: $(imageRepository)

              tags: |
                $(Build.BuildNumber)
                latest

          # =====================================
          # ACR BUILD
          # =====================================

          - task: Docker@2

            displayName: ACR Build

            condition: eq(lower(variables['enableAcr']), 'true')

            inputs:

              command: build

              containerRegistry: $(acrServiceConnection)

              repository: $(acrRepository)

              dockerfile: '$(Build.SourcesDirectory)/Dockerfile'

              buildContext: '$(Build.SourcesDirectory)'

              tags: |
                $(Build.BuildNumber)
                latest

          # =====================================
          # ACR PUSH
          # =====================================

          - task: Docker@2

            displayName: ACR Push

            condition: eq(lower(variables['enableAcr']), 'true')

            inputs:

              command: push

              containerRegistry: $(acrServiceConnection)

              repository: $(acrRepository)

              tags: |
                $(Build.BuildNumber)
                latest