trigger: none

parameters:
- name: environment
  type: string
  default: dev

pool:
  vmImage: ubuntu-latest

variables:
- group: employeeprofileapp-${{ parameters.environment }}-vars

stages:

- stage: Deploy
  displayName: Deploy To AKS

  jobs:

  - job: HelmDeploy
    displayName: Helm Deployment

    steps:

    - checkout: self

    - task: AzureCLI@2
      displayName: AKS Login

      inputs:
        azureSubscription: 'AKS SCN'
        scriptType: bash
        scriptLocation: inlineScript

        inlineScript: |

          echo "Azure Login Successful"

          az account show

          az aks get-credentials \
            --resource-group $(aksResourceGroup) \
            --name $(aksClusterName) \
            --overwrite-existing

          kubectl get nodes

    - task: HelmInstaller@1
      displayName: Install Helm

      inputs:
        helmVersionToInstall: latest

    - script: |

        echo "Starting Helm deployment..."

        helm upgrade --install $(helmReleaseName) ./helm/employeeprofileapp \
          --namespace $(namespace) \
          --create-namespace \
          -f ./helm/employeeprofileapp/values-${{ parameters.environment }}.yaml \
          --set image.repository=$(acrLoginServer)/$(imageRepository) \
          --set image.tag=$(Build.BuildId) \
          --wait \
          --timeout 10m

      displayName: Helm Upgrade Install

    - script: |

        echo "Validating deployment..."

        kubectl get pods -n $(namespace)

        kubectl rollout status deployment/employeeprofileapp \
          -n $(namespace) \
          --timeout=300s

      displayName: Verify Deployment