trigger:
- main

parameters:
- name: environment
  type: string
  default: dev

pool:
  vmImage: ubuntu-latest

variables:
- group: employeeprofileapp-${{ parameters.environment }}-vars

stages:

- stage: Terraform
  displayName: Terraform Deployment

  jobs:
  - job: TerraformApply
    displayName: Terraform Apply

    steps:

    - checkout: self

    - task: TerraformInstaller@1
      displayName: Install Terraform
      inputs:
        terraformVersion: latest

    - task: AzureCLI@2
      displayName: Terraform Apply
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        workingDirectory: $(terraformWorkingDirectory)

        inlineScript: |

          echo "Checking TF_VAR_secret_data"

          if [ -z "$TF_VAR_secret_data" ]; then
            echo "TF_VAR_secret_data is EMPTY"
          else
            echo "TF_VAR_secret_data is PRESENT"
          fi

          terraform init

          terraform validate

          terraform plan -input=false -out=tfplan

          terraform apply -input=false -auto-approve tfplan

          az aks get-credentials \
            --resource-group employeeprofileapp-dev-rg \
            --name employeeprofileapp-dev-aks \
            --admin \
            --overwrite-existing

          kubectl get nodes

      env:
        TF_VAR_secret_data: $(TF_VAR_secret_data)